server:
  port: 8040
spring:
#  application:
#    name: service-config
  cloud:
    config:
      server:
        git:
          uri: http://10.3.1.5:90/niebiaofei/config-file.git     # 配置git仓库的地址
          # search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码
